# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import node_pb2 as node__pb2


class RaftServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEntries = channel.unary_unary(
                '/RaftService/AppendEntries',
                request_serializer=node__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=node__pb2.AppendEntriesResponse.FromString,
                )
        self.RequestVote = channel.unary_unary(
                '/RaftService/RequestVote',
                request_serializer=node__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=node__pb2.RequestVoteResponse.FromString,
                )
        self.ServeClient = channel.unary_unary(
                '/RaftService/ServeClient',
                request_serializer=node__pb2.ServeClientArgs.SerializeToString,
                response_deserializer=node__pb2.ServeClientReply.FromString,
                )
        self.Recovery = channel.unary_unary(
                '/RaftService/Recovery',
                request_serializer=node__pb2.RecoverRequest.SerializeToString,
                response_deserializer=node__pb2.RecoverReply.FromString,
                )
        self.ReplicateLogs = channel.unary_unary(
                '/RaftService/ReplicateLogs',
                request_serializer=node__pb2.LogReplicationRequest.SerializeToString,
                response_deserializer=node__pb2.LogReplicationResponse.FromString,
                )


class RaftServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=node__pb2.AppendEntriesRequest.FromString,
                    response_serializer=node__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=node__pb2.RequestVoteRequest.FromString,
                    response_serializer=node__pb2.RequestVoteResponse.SerializeToString,
            ),
            'ServeClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeClient,
                    request_deserializer=node__pb2.ServeClientArgs.FromString,
                    response_serializer=node__pb2.ServeClientReply.SerializeToString,
            ),
            'Recovery': grpc.unary_unary_rpc_method_handler(
                    servicer.Recovery,
                    request_deserializer=node__pb2.RecoverRequest.FromString,
                    response_serializer=node__pb2.RecoverReply.SerializeToString,
            ),
            'ReplicateLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateLogs,
                    request_deserializer=node__pb2.LogReplicationRequest.FromString,
                    response_serializer=node__pb2.LogReplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/AppendEntries',
            node__pb2.AppendEntriesRequest.SerializeToString,
            node__pb2.AppendEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/RequestVote',
            node__pb2.RequestVoteRequest.SerializeToString,
            node__pb2.RequestVoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/ServeClient',
            node__pb2.ServeClientArgs.SerializeToString,
            node__pb2.ServeClientReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/Recovery',
            node__pb2.RecoverRequest.SerializeToString,
            node__pb2.RecoverReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RaftService/ReplicateLogs',
            node__pb2.LogReplicationRequest.SerializeToString,
            node__pb2.LogReplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
